version: '3.8'

services:
  backend:
    build: ./server
    container_name: team7-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
    networks:
      - team7-network
    volumes:
      - ./server:/app
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 dit826.asgi:application"

  frontend:
    build: ./web
    container_name: team7-frontend
    ports:
      - "5173:5173"
    networks:
      - team7-network
    volumes:
      - ./web:/client
      - /client/node_modules
    depends_on:
      - backend
      