# Generated by Django 5.2.8 on 2025-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
