# Generated by Django on 2025-12-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_trainedmodel_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainedmodel",
            name="csv_file",
            field=models.FileField(upload_to="training_data/", null=True, blank=True),
        ),
    ]
