# Generated by Django 5.2.8 on 2025-12-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprediction',
            name='target_letter',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
