# Generated by Django 5.2.8 on 2025-12-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprediction_target_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='classification_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='confusion_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='recall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
