# Generated by Django 5.2.8 on 2025-12-18 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trainedmodel_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='previous_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='api.trainedmodel'),
        ),
    ]
