# Generated by Django 5.2.8 on 2025-12-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_trainedmodel_previous_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                (
                    "example_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="label_examples/"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainedmodel",
            name="active_labels",
            field=models.ManyToManyField(
                blank=True, related_name="models", to="api.label"
            ),
        ),
    ]
