# Generated by Django 5.2.8 on 2026-01-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_label_trainedmodel_active_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainedmodel",
            name="validation_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
