apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: team7
spec:
  type: LoadBalancer
  loadBalancerIP: 34.88.162.37
  selector:
    app: backend 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000