apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: team7
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: frontend
          image: registry.git.chalmers.se/courses/dit826/2025/team7/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://34.88.162.37"